--- 
after_success: 
  - "wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh"
  - "bash upload.sh MieSimulatorGUI*.AppImage*"
before_install: 
  - "sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y"
  - "sudo apt-get update -qq"
branches: 
  except: 
    - ~
    - "/^(?i:continuous)/"
compiler: 
  - gcc
  - clang
fi: ~
? "if [ $TRAVIS_OS_NAME = 'osx' ]"
: then
? "if [$TRAVIS_OS_NAME = 'linux']"
: then
install: 
  - "sudo apt-get -y install qt510base libgl1-mesa-dev"
  - "source /opt/qt*/bin/qt*-env.sh"
jobs: 
  include: 
    - 
      dist: trusty
      os: linux
    - 
      os: osx
      osx_image: xcode7.2
language: cpp
os: 
  - linux
  - osx
script: 
  - "qmake \"CONFIG+=MieSimulatorGUI\" src/MieSimulatorGUI.pro"
  - "make -j$(nproc)"
