language: cpp

matrix:
  include:
    - env: OS=linux
      os: linux
      compiler: gcc
      dist: trusty
    - env: OS=osx
      os: osx
      compiler: clang

before_install:
 - sudo true;
 - if [ "$OS" = "linux" ]; then 
     sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y;
     sudo apt-get update -qq;
   fi
   
 - if [ "$OS" = "osx" ]; then  
     QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.13;
   fi
 
install:
 - if [ "$OS" = "linux" ]; then  
     sudo apt-get -y install qt510base libgl1-mesa-dev;
     source /opt/qt*/bin/qt*-env.sh;
   fi

 - if [ "$OS" = "osx" ]; then  
     ./configure -platform macx-clang QMAKE_APPLE_DEVICE_ARCHS="x86_64 x86_64h";
   fi
   
script:
 
 - if [ "$OS" = "linux" ]; then     
     qmake "CONFIG+=MieSimulatorGUI" src/MieSimulatorGUI.pro; 
     make -j$(nproc);
     make INSTALL_ROOT=appdir -j$(nproc) install ; 
     find appdir/;
     wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
     chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
     ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/MieSimulatorGUI.desktop -appimage;
   fi

 - if [ "$OS" = "osx" ]; then     
     qmake -spec macx-xcode src/MieSimulatorGUI.pro;      
   fi
   
after_success: 
 - if [ "$OS" = "linux" ]; then 
     wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh;
     bash upload.sh MieSimulatorGUI*.AppImage*;
   fi