language: cpp

os:
  - linux
  - osx


if ["$TRAVIS_OS_NAME" = "linux": then  
before_install:
 sudo:true
 sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
 sudo apt-get update -qq
install:
 sudo apt-get -y install qt510base libgl1-mesa-dev
 source /opt/qt*/bin/qt*-env.sh
script:
  - qmake "CONFIG+=MieSimulatorGUI" src/MieSimulatorGUI.pro
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
   -./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/MieSimulatorGUI.desktop -appimage
after_success: 
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh MieSimulatorGUI*.AppImage*
fi: