language: cpp

matrix:
  include:
    - env: OS=linux
      os: linux
      compiler: gcc
      dist: trusty
      sudo: true
      before_install:
      - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
      - sudo apt-get update -qq
      - sudo apt-get -y install qt510base libgl1-mesa-dev
      - source /opt/qt*/bin/qt*-env.sh
    - env: OS=osx
      os: osx
      osx_image: xcode7.2
      compiler: clang
      before_install:
      - brew install qt5
      - brew link qt5 --force
    - env: OS=windows
      os: windows
      before_install:
      - dir C:/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/10.0.17134.0/x64
      - cmd.exe /C 'cd && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86 && cd && cd "C:/Users/travis/build/VirtualPhotonics/MieSimulatorGUI" && dir'
      - curl -vLO http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe 
      - "./qt-unified-windows-x86-online.exe --verbose --script qt-installer-windows.qs"
      - ls -la C:/Qt/5.12.3/msvc2017/bin/qtenv2.bat
   
script:
 
 - if [ "$OS" = "linux" ]; then     
     qmake "CONFIG+=MieSimulatorGUI" src/MieSimulatorGUI.pro; 
     make -j$(nproc);
     make INSTALL_ROOT=appdir -j$(nproc) install ; 
     find appdir/;
     wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
     chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
     ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/MieSimulatorGUI.desktop -appimage;
   fi

 - if [ "$OS" = "osx" ]; then
     make clean
     qmake -config release     
     qmake -spec macx-xcode src/MieSimulatorGUI.pro;
     xcodebuild -list -project MieSimulatorGUI_continuous.xcodeproj;
     xcodebuild -scheme MieSimulatorGUI_continuous build;      
   fi
   
 - if [ "$OS" = "windows" ]; then     
     cmd.exe /C 'cd && "C:\Qt\5.12.3\msvc2017\bin\qtenv2.bat" && cd && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86 && cd "C:\Users\travis\build\VirtualPhotonics\MieSimulatorGUI" && cd && qmake MieSimulatorGUI.pro && nmake';     
   fi

after_success: 
 - if [ "$OS" = "linux" ]; then 
     wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh;
     bash upload.sh MieSimulatorGUI*.AppImage*;
   fi