language: cpp

os:
  - linux
  - osx


before_install:
 if [ "$TRAVIS_OS_NAME" = "linux"]; then        
     - sudo:true
     - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
     - sudo apt-get update -qq; 
 fi

    
install:
 if [ "$TRAVIS_OS_NAME" = "linux"]; then 
   - sudo apt-get -y install qt510base libgl1-mesa-dev
   - source /opt/qt*/bin/qt*-env.sh;
 fi
 
script:
 if [ "$TRAVIS_OS_NAME" = "linux"]; then 
  - qmake "CONFIG+=MieSimulatorGUI" src/MieSimulatorGUI.pro
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  -./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/MieSimulatorGUI.desktop -appimage
  fi
  
after_success:
 if [ "$TRAVIS_OS_NAME" = "linux"]; then 
   - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
   - bash upload.sh MieSimulatorGUI*.AppImage*
 fi